---
- name: Do CRUD operations on the Book endpoint
  hosts: localhost
  tasks:
    - name: Create a new book
      book:
        title: '{{ item.title }}'
        author: '{{ item.author }}'
        summary: '{{ item.summary }}'
      with_items:
        - { 'title': 'Un titre', 'author': 'Un auteur', 'summary': 'Un resume' }
        - { 'title': 'Deux titres', 'author': 'Deux auteurs', 'summary': 'Deux resumes' }
        - { 'title': 'Trois titres', 'author': 'Trois auteurs', 'summary': 'Trois resumes' }
